# Generated by Django 4.2.1 on 2023-06-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_detail', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemslist',
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartUser',
        ),
    ]
