# Generated by Django 4.2.1 on 2023-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_detail', '0010_cartitemslist_user_coupon_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='delivery_charge',
            new_name='discount_amount',
        ),
    ]
