# Generated by Django 4.2.1 on 2023-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(to='products.productcolors'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sizes',
            field=models.ManyToManyField(to='products.productsizes'),
        ),
    ]
