# Generated by Django 4.2.1 on 2023-05-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_colors_product_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default=None, upload_to='images/products')),
                ('image_2', models.ImageField(default=None, upload_to='images/products')),
                ('image_3', models.ImageField(default=None, upload_to='images/products')),
                ('colors', models.ManyToManyField(to='products.productcolors')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
