# Generated by Django 4.2.1 on 2023-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_product_colors_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sizes',
        ),
    ]
