# Generated by Django 4.2.1 on 2023-05-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimages_colors_productimages_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='product_thumbnail',
        ),
    ]
