# Generated by Django 4.2.1 on 2023-05-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_images_product_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='size',
            field=models.ManyToManyField(to='products.productsizes'),
        ),
    ]
