# Generated by Django 4.2.1 on 2023-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productbrands_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/products'),
        ),
    ]
